#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'
import { createClient } from '@supabase/supabase-js'
import chalk from 'chalk'
import { escSql } from './lib/ingest-diff.js'

type NonMusicalEvent = {
  title: string
  category: string
  stage: string
  day: string
  start_time: string
  end_time: string
}

type NonMusicalFile = {
  festival_slug: string
  events: NonMusicalEvent[]
}

const args = process.argv.slice(2)
const fileArg = args.find(a => a.startsWith('--file='))?.split('=').slice(1).join('=')
const dryRun = args.includes('--dry-run')

if (!fileArg) {
  console.log(`Usage:
  npm run import-nonmusical -- --file=<path.json>
  npm run import-nonmusical -- --file=<path.json> --dry-run`)
  process.exit(0)
}

const data: NonMusicalFile = JSON.parse(readFileSync(fileArg, 'utf-8'))
const { festival_slug: slug, events } = data

const supabaseUrl = process.env.VITE_SUPABASE_URL
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!supabaseUrl || !serviceKey) {
  console.error(chalk.red('Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local'))
  process.exit(1)
}
const supabase = createClient(supabaseUrl, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } })

async function main() {
  const { data: festival } = await supabase.from('festivals').select('id').eq('slug', slug).single()
  if (!festival) {
    console.error(chalk.red(`Festival not found for slug: ${slug}`))
    process.exit(1)
  }

  const { data: existingStages } = await supabase
    .from('stages')
    .select('name, sort_order')
    .eq('festival_id', festival.id)
  const existingStageNames = new Set((existingStages ?? []).map(s => s.name))
  const maxSortOrder = (existingStages ?? []).reduce((mx, s) => Math.max(mx, s.sort_order), 0)

  const uniqueStages = [...new Set(events.map(e => e.stage))]
  const newStages = uniqueStages.filter(name => !existingStageNames.has(name))

  console.log(`Festival: ${slug}`)
  console.log(`Events: ${events.length}`)
  console.log(`Stages referenced: ${uniqueStages.length} (${newStages.length} new)`)
  if (newStages.length > 0) console.log(`  New: ${newStages.join(', ')}`)

  const lines: string[] = []
  lines.push(`-- Auto-generated by import-nonmusical.ts on ${new Date().toISOString().split('T')[0]}`)
  lines.push(`-- Source: ${fileArg}`)
  lines.push(`-- Festival: ${slug}`)
  lines.push('')
  lines.push(`DO $$ DECLARE fest_id uuid; stage_ids jsonb := '{}';`)
  lines.push(`BEGIN`)
  lines.push(`  SELECT id INTO fest_id FROM festivals WHERE slug = '${escSql(slug)}';`)
  lines.push('')

  if (newStages.length > 0) {
    lines.push('  -- New stages (non-musical)')
    newStages.forEach((name, i) => {
      lines.push(`  INSERT INTO stages (festival_id, name, sort_order)`)
      lines.push(`  VALUES (fest_id, '${escSql(name)}', ${maxSortOrder + 1 + i})`)
      lines.push(`  ON CONFLICT (festival_id, name) DO NOTHING;`)
    })
    lines.push('')
  }

  lines.push(`  SELECT jsonb_object_agg(name, id) INTO stage_ids FROM stages WHERE festival_id = fest_id;`)
  lines.push('')
  lines.push(`  -- Non-musical events (idempotent: skip if an identical row already exists)`)
  for (const e of events) {
    const stageRef = `(stage_ids->>'${escSql(e.stage)}')::uuid`
    lines.push(`  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, performance_type, is_music_set)`)
    lines.push(`  SELECT fest_id, ${stageRef}, '${escSql(e.title)}', '${e.day}', '${e.start_time}', '${e.end_time}', NULL, false`)
    lines.push(`  WHERE NOT EXISTS (`)
    lines.push(`    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = '${escSql(e.title)}' AND day = '${e.day}'`)
    lines.push(`      AND start_time = '${e.start_time}' AND stage_id = ${stageRef}`)
    lines.push(`  );`)
  }
  lines.push('')
  lines.push(`END $$;`)
  lines.push('')

  const sql = lines.join('\n')
  const outPath = 'supabase/migrations/026_hospitality_nonmusical.sql'

  if (dryRun) {
    console.log(chalk.yellow('\n--- DRY RUN: generated SQL ---\n'))
    console.log(sql)
    return
  }

  writeFileSync(outPath, sql)
  console.log(chalk.green(`\nWrote ${outPath}`))
}

main()
