-- Auto-generated by import-nonmusical.ts on 2026-06-23
-- Source: scraped/hospitality-on-the-beach-2026-nonmusical.json
-- Festival: hospitality-on-the-beach-2026

DO $$ DECLARE fest_id uuid; stage_ids jsonb := '{}';
BEGIN
  SELECT id INTO fest_id FROM festivals WHERE slug = 'hospitality-on-the-beach-2026';

  SELECT jsonb_object_agg(name, id) INTO stage_ids FROM stages WHERE festival_id = fest_id;

  -- Non-musical events (idempotent: skip if an identical row already exists)
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Pier')::uuid, 'Yoga', '2026-07-01', '10:00', '11:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yoga' AND day = '2026-07-01'
      AND start_time = '10:00' AND stage_id = (stage_ids->>'The Pier')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Tisno Bridge (Off-Site)')::uuid, 'Run Club', '2026-07-01', '10:30', '11:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Run Club' AND day = '2026-07-01'
      AND start_time = '10:30' AND stage_id = (stage_ids->>'Tisno Bridge (Off-Site)')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Sound Bath', '2026-07-01', '11:00', '12:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Sound Bath' AND day = '2026-07-01'
      AND start_time = '11:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-01', '12:00', '13:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-01'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Meditation', '2026-07-01', '13:00', '14:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Meditation' AND day = '2026-07-01'
      AND start_time = '13:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-01', '14:00', '15:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-01'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Breathing Reset', '2026-07-01', '15:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Breathing Reset' AND day = '2026-07-01'
      AND start_time = '15:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Yin Yoga (Settle Into Stillness)', '2026-07-01', '16:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yin Yoga (Settle Into Stillness)' AND day = '2026-07-01'
      AND start_time = '16:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Playlist', '2026-07-01', '12:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Playlist' AND day = '2026-07-01'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Olive Grove')::uuid, 'Bangers Vs Clangers Sign Up', '2026-07-02', '14:00', '15:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Bangers Vs Clangers Sign Up' AND day = '2026-07-02'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'Olive Grove')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Olive Grove')::uuid, 'Bangers Vs Clangers Tournament', '2026-07-02', '15:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Bangers Vs Clangers Tournament' AND day = '2026-07-02'
      AND start_time = '15:00' AND stage_id = (stage_ids->>'Olive Grove')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Pier')::uuid, 'Yoga', '2026-07-02', '10:00', '11:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yoga' AND day = '2026-07-02'
      AND start_time = '10:00' AND stage_id = (stage_ids->>'The Pier')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Tisno Bridge (Off-Site)')::uuid, 'Run Club', '2026-07-02', '10:30', '11:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Run Club' AND day = '2026-07-02'
      AND start_time = '10:30' AND stage_id = (stage_ids->>'Tisno Bridge (Off-Site)')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Sound Bath', '2026-07-02', '11:00', '12:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Sound Bath' AND day = '2026-07-02'
      AND start_time = '11:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-02', '12:00', '13:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-02'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Swim & Stretch', '2026-07-02', '13:00', '14:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Swim & Stretch' AND day = '2026-07-02'
      AND start_time = '13:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-02', '14:00', '15:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-02'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Tea & Conversation Cards', '2026-07-02', '15:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Tea & Conversation Cards' AND day = '2026-07-02'
      AND start_time = '15:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Breathing Reset', '2026-07-02', '16:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Breathing Reset' AND day = '2026-07-02'
      AND start_time = '16:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-02', '17:00', '18:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-02'
      AND start_time = '17:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Playlist', '2026-07-02', '12:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Playlist' AND day = '2026-07-02'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Tisno Bridge (Off-Site)')::uuid, 'Run Club', '2026-07-03', '10:30', '11:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Run Club' AND day = '2026-07-03'
      AND start_time = '10:30' AND stage_id = (stage_ids->>'Tisno Bridge (Off-Site)')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Pier')::uuid, 'Yoga', '2026-07-03', '10:00', '11:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yoga' AND day = '2026-07-03'
      AND start_time = '10:00' AND stage_id = (stage_ids->>'The Pier')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Sound Bath', '2026-07-03', '11:00', '12:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Sound Bath' AND day = '2026-07-03'
      AND start_time = '11:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-03', '12:00', '13:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-03'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Olive Grove - The Deep End')::uuid, 'DNB Karaoke Sign Up', '2026-07-03', '13:00', '13:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'DNB Karaoke Sign Up' AND day = '2026-07-03'
      AND start_time = '13:00' AND stage_id = (stage_ids->>'Olive Grove - The Deep End')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Cacao & Movement', '2026-07-03', '13:00', '14:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Cacao & Movement' AND day = '2026-07-03'
      AND start_time = '13:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Olive Grove - The Deep End')::uuid, 'DNB Karaoke', '2026-07-03', '13:30', '15:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'DNB Karaoke' AND day = '2026-07-03'
      AND start_time = '13:30' AND stage_id = (stage_ids->>'Olive Grove - The Deep End')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-03', '14:00', '15:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-03'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Meditation', '2026-07-03', '15:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Meditation' AND day = '2026-07-03'
      AND start_time = '15:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Playlist', '2026-07-03', '12:00', '16:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Playlist' AND day = '2026-07-03'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Yin Yoga (Settle Into Stillness)', '2026-07-03', '16:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yin Yoga (Settle Into Stillness)' AND day = '2026-07-03'
      AND start_time = '16:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-03', '17:00', '18:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-03'
      AND start_time = '17:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Playlist', '2026-07-04', '12:00', '15:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Playlist' AND day = '2026-07-04'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Women in D&B Q&A', '2026-07-04', '15:30', '16:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Women in D&B Q&A' AND day = '2026-07-04'
      AND start_time = '15:30' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Women in D&B Open Decks', '2026-07-04', '16:30', '18:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Women in D&B Open Decks' AND day = '2026-07-04'
      AND start_time = '16:30' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Olive Grove - Drum & Bass Classics')::uuid, 'Bangers Vs Clangers Competition Winner', '2026-07-04', '15:30', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Bangers Vs Clangers Competition Winner' AND day = '2026-07-04'
      AND start_time = '15:30' AND stage_id = (stage_ids->>'Olive Grove - Drum & Bass Classics')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Pier')::uuid, 'Yoga', '2026-07-04', '10:00', '11:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yoga' AND day = '2026-07-04'
      AND start_time = '10:00' AND stage_id = (stage_ids->>'The Pier')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Sound Bath', '2026-07-04', '11:00', '12:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Sound Bath' AND day = '2026-07-04'
      AND start_time = '11:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-04', '12:00', '13:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-04'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Swim & Stretch', '2026-07-04', '13:00', '14:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Swim & Stretch' AND day = '2026-07-04'
      AND start_time = '13:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-04', '14:00', '15:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-04'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Shake It Out', '2026-07-04', '15:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Shake It Out' AND day = '2026-07-04'
      AND start_time = '15:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Self-Massage Workshop', '2026-07-04', '16:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Self-Massage Workshop' AND day = '2026-07-04'
      AND start_time = '16:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-04', '17:00', '18:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-04'
      AND start_time = '17:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Pier')::uuid, 'Yin Yoga', '2026-07-05', '10:00', '11:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Yin Yoga' AND day = '2026-07-05'
      AND start_time = '10:00' AND stage_id = (stage_ids->>'The Pier')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Sound Bath', '2026-07-05', '11:00', '12:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Sound Bath' AND day = '2026-07-05'
      AND start_time = '11:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-05', '12:00', '13:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-05'
      AND start_time = '12:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Breathwork', '2026-07-05', '13:00', '14:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Breathwork' AND day = '2026-07-05'
      AND start_time = '13:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-05', '14:00', '15:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-05'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Creative Chill (Writing / Drawing)', '2026-07-05', '15:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Creative Chill (Writing / Drawing)' AND day = '2026-07-05'
      AND start_time = '15:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Closing Circle', '2026-07-05', '16:00', '17:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Closing Circle' AND day = '2026-07-05'
      AND start_time = '16:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'The Wellness Zone')::uuid, 'Chill Lounge', '2026-07-05', '17:00', '18:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Chill Lounge' AND day = '2026-07-05'
      AND start_time = '17:00' AND stage_id = (stage_ids->>'The Wellness Zone')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Boat Party - Bangers vs. Clangers')::uuid, 'Featuring You! Hosted by House of Dinosaur', '2026-07-04', '12:30', '15:30', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Featuring You! Hosted by House of Dinosaur' AND day = '2026-07-04'
      AND start_time = '12:30' AND stage_id = (stage_ids->>'Boat Party - Bangers vs. Clangers')::uuid
  );
  INSERT INTO sets (festival_id, stage_id, artist_name, day, start_time, end_time, is_live, is_music_set)
  SELECT fest_id, (stage_ids->>'Wabi Sabi')::uuid, 'Hospital30 Birthday Party (hosted by House of Dinosaur)', '2026-07-05', '14:00', '16:00', false, false
  WHERE NOT EXISTS (
    SELECT 1 FROM sets WHERE festival_id = fest_id AND artist_name = 'Hospital30 Birthday Party (hosted by House of Dinosaur)' AND day = '2026-07-05'
      AND start_time = '14:00' AND stage_id = (stage_ids->>'Wabi Sabi')::uuid
  );

END $$;
